<?php
/*************************************************************************************
 * ucc.php
 * -------
 *
 * Author: Marzo Junior (marzojr@yahoo.com)
 * Copyright: (c) 2006 Marzo Junior (http://seventowers.u7feudallands.com)
 * Release Version: 0.1.0
 * CVS Revision Version: $Revision: 0.1.0 $
 * Date Started: 2006/11/05
 * Last Modified: $Date: 2006/11/05 16:24:35 $
 *
 * UCC language file for GeSHi.
 *
 * CHANGES
 * -------
 * 2006/11/05 (0.1.0)
 *  -  First Release
 *
 * TODO (updated 2004/11/27)
 * -------------------------
 *
 *************************************************************************************
 *
 *		This file is part of GeSHi.
 *
 *   GeSHi is free software; you can redistribute it and/or modify
 *   it under the terms of the GNU General Public License as published by
 *   the Free Software Foundation; either version 2 of the License, or
 *   (at your option) any later version.
 *
 *   GeSHi is distributed in the hope that it will be useful,
 *   but WITHOUT ANY WARRANTY; without even the implied warranty of
 *   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *   GNU General Public License for more details.
 *
 *   You should have received a copy of the GNU General Public License
 *   along with GeSHi; if not, write to the Free Software
 *   Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 ************************************************************************************/

$language_data = array (
	'LANG_NAME' => 'Usecode C',
	'COMMENT_SINGLE' => array(1 => '//'),
	'COMMENT_MULTI' => array('/*' => '*/'),
	'CASE_KEYWORDS' => GESHI_CAPS_NO_CHANGE,
	'QUOTEMARKS' => array('"'),
	'ESCAPE_CHAR' => '\\',
	'KEYWORDS' => array(
		1 => array(				// Language constructs
			'with', 'do', 'while', 'var', 'void', 'to', 'ticks', 'switch', 'string', 'static',
			'shape', 'object', 'script', 'return', 'response', 'remove', 'new',
			'int', 'char', 'byte', 'long', 'in', 'if', 'goto', 'for', 'extern', 'abort',
			'enum', 'else', 'delete', 'default', 'converse', 'continue', 'after',
			'const', 'class', 'struct', 'alias', 'case', 'break', 'nested'
			),
		2 => array(				// Language elements
			'true', 'this', 'say', 'run_script', 'original', 'message', 'item',
			'hide', 'gflags', 'false', 'event', 'add', 'user_choice',
			),
		3 => array(				// Script commands
			'weather', 'wait', 'actor', 'step', 'speech', 'sfx', 'setegg',
			'rise', /*'resurrect',*/ 'reset', 'repeat', 'previous', 'nop',
			'nohalt', 'next', 'music', 'minutes', 'hours', 'hit', 'hatch',
			'frame', 'finish', 'face', 'descent', 'cycle', /*'continue',*/ 'call',
			'attack', 'near', 'far',
			),
		4 => array(				// Predefined script constants
			'west', 'sw', 'south', 'se', 'nw', 'north', 'ne', 'east', 'standing',
			'step_right', 'step_left', 'ready', 'raise_1h', 'reach_1h', 'strike_1h',
			'raise_2h', 'reach_2h', 'strike_2h', 'sitting', 'bowing', 'kneeling',
			'sleeping', 'cast_up', 'cast_out',
			),
		5 => array(				// Intrinsics
			'UI_add_answer',
			   'add_answer',
			'UI_add_cont_items',
			   'add_cont_items',
			'UI_add_party_items',
			   'add_party_items',
			'UI_add_spell',
			   'add_spell',
			'UI_add_to_keyring',
			   'add_to_keyring',
			'UI_add_to_party',
			   'add_to_party',
			'UI_advance_time',
			   'advance_time',
			'UI_ambient_light',
			   'ambient_light',
			'UI_a_or_an',
			   'a_or_an',
			'UI_apply_damage',
			   'apply_damage',
			'UI_approach_avatar',
			   'approach_avatar',
			'UI_armageddon',
			   'armageddon',
			'UI_attack_avatar',
			   'attack_avatar',
			'UI_attack_object',
			   'attack_object',
			'UI_begin_casting_mode',
			   'begin_casting_mode',
			'UI_book_mode',
			   'book_mode',
			'UI_book_mode_ex',
			   'book_mode_ex',
			'UI_call_guards',
			   'call_guards',
			'UI_can_avatar_reach_pos',
			   'can_avatar_reach_pos',
			'UI_cause_light',
			   'cause_light',
			'UI_center_view',
			   'center_view',
			'UI_change_npc_face0',
			   'change_npc_face0',
			'UI_change_npc_face1',
			   'change_npc_face1',
			'UI_clear_answers',
			   'clear_answers',
			'UI_clear_item_flag',
			   'clear_item_flag',
			'UI_clear_item_say',
			   'clear_item_say',
			'UI_click_on_item',
			   'click_on_item',
			'UI_clone',
			   'clone',
			'UI_close_gump',
			   'close_gump',
			'UI_close_gumps',
			   'close_gumps',
			'UI_count_objects',
			   'count_objects',
			'UI_create_barge_object',
			   'create_barge_object',
			'UI_create_new_object2',
			   'create_new_object2',
			'UI_create_new_object',
			   'create_new_object',
			'UI_delayed_execute_usecode_array',
			   'delayed_execute_usecode_array',
			'UI_die_roll',
			   'die_roll',
			'UI_direction_from',
			   'direction_from',
			'UI_display_area',
			   'display_area',
			'UI_display_map',
			   'display_map',
			'UI_display_map_ex',
			   'display_map_ex',
			'UI_display_runes',
			   'display_runes',
			'UI_earthquake',
			   'earthquake',
			'UI_end_conversation',
			   'end_conversation',
			'UI_error_message',
			   'error_message',
			'UI_execute_usecode_array',
			   'execute_usecode_array',
			'UI_fade_palette',
			   'fade_palette',
			'UI_find_direction',
			   'find_direction',
			'UI_find_nearby_avatar',
			   'find_nearby_avatar',
			'UI_find_nearby',
			   'find_nearby',
			'UI_find_nearest',
			   'find_nearest',
			'UI_find_object',
			   'find_object',
			'UI_fire_projectile',
			   'fire_projectile',
			'UI_flash_mouse',
			   'flash_mouse',
			'UI_game_hour',
			   'game_hour',
			'UI_game_minute',
			   'game_minute',
			'UI_get_alignment',
			   'get_alignment',
			'UI_get_array_size',
			   'get_array_size',
			'UI_get_attack_mode',
			   'get_attack_mode',
			'UI_get_avatar_ref',
			   'get_avatar_ref',
			'UI_get_barge',
			   'get_barge',
			'UI_get_body_npc',
			   'get_body_npc',
			'UI_get_container',
			   'get_container',
			'UI_get_cont_items',
			   'get_cont_items',
			'UI_get_dead_party',
			   'get_dead_party',
			'UI_get_distance',
			   'get_distance',
			'UI_get_item_flag',
			   'get_item_flag',
			'UI_get_item_frame',
			   'get_item_frame',
			'UI_get_item_frame_rot',
			   'get_item_frame_rot',
			'UI_get_item_quality',
			   'get_item_quality',
			'UI_get_item_quantity',
			   'get_item_quantity',
			'UI_get_item_shape',
			   'get_item_shape',
			'UI_get_item_weight',
			   'get_item_weight',
			'UI_get_lift',
			   'get_lift',
			'UI_get_map_num',
			   'get_map_num',
			'UI_get_music_track',
			   'get_music_track',
			'UI_get_npc_id',
			   'get_npc_id',
			'UI_get_npc_name',
			   'get_npc_name',
			'UI_get_npc_number',
			   'get_npc_number',
			'UI_get_npc_object',
			   'get_npc_object',
			'UI_get_npc_prop',
			   'get_npc_prop',
			'UI_get_npc_warmth',
			   'get_npc_warmth',
			'UI_get_object_position',
			   'get_object_position',
			'UI_get_oppressor',
			   'get_oppressor',
			'UI_get_party_list2',
			   'get_party_list2',
			'UI_get_party_list',
			   'get_party_list',
			'UI_get_random',
			   'get_random',
			'UI_get_readied',
			   'get_readied',
			'UI_get_schedule_type',
			   'get_schedule_type',
			'UI_get_skin_colour',
			   'get_skin_colour',
			'UI_get_speech_track',
			   'get_speech_track',
			'UI_get_temperature',
			   'get_temperature',
			'UI_get_temperature_zone',
			   'get_temperature_zone',
			'UI_get_timer',
			   'get_timer',
			'UI_get_usecode_fun',
			   'get_usecode_fun',
			'UI_get_weapon',
			   'get_weapon',
			'UI_get_weather',
			   'get_weather',
			'UI_give_last_created',
			   'give_last_created',
			'UI_halt_scheduled',
			   'halt_scheduled',
			'UI_has_spell',
			   'has_spell',
			'UI_in_combat',
			   'in_combat',
			'UI_infravision',
			   'infravision',
			'UI_in_gump_mode',
			   'in_gump_mode',
			'UI_init_conversation',
			   'init_conversation',
			'UI_input_numeric_value',
			   'input_numeric_value',
			'UI_in_usecode',
			   'in_usecode',
			'UI_in_usecode_path',
			   'in_usecode_path',
			'UI_is_dead',
			   'is_dead',
			'UI_is_dest_reachable',
			   'is_dest_reachable',
			'UI_is_not_blocked',
			   'is_not_blocked',
			'UI_is_npc',
			   'is_npc',
			'UI_is_on_keyring',
			   'is_on_keyring',
			'UI_is_pc_female',
			   'is_pc_female',
			'UI_is_pc_inside',
			   'is_pc_inside',
			'UI_is_readied',
			   'is_readied',
			'UI_is_water',
			   'is_water',
			'UI_item_say',
			   'item_say',
			'UI_kill_npc',
			   'kill_npc',
			'UI_lightning',
			   'lightning',
			'UI_mark_virtue_stone',
			   'mark_virtue_stone',
			'UI_modify_schedule',
			   'modify_schedule',
			'UI_mouse_exists',
			   'mouse_exists',
			'UI_move_object',
			   'move_object',
			'UI_nap_time',
			   'nap_time',
			'UI_npc_nearby2',
			   'npc_nearby2',
			'UI_npc_nearby',
			   'npc_nearby',
			'UI_obj_sprite_effect',
			   'obj_sprite_effect',
			'UI_on_barge',
			   'on_barge',
			'UI_part_of_day',
			   'part_of_day',
			'UI_path_run_usecode',
			   'path_run_usecode',
			'UI_play_music',
			   'play_music',
			'UI_play_sound_effect2',
			   'play_sound_effect2',
			'UI_play_sound_effect',
			   'play_sound_effect',
			'UI_pop_answers',
			   'pop_answers',
			'UI_printf',
			   'printf',
			'UI_push_answers',
			   'push_answers',
			'UI_recall_virtue_stone',
			   'recall_virtue_stone',
			'UI_reduce_health',
			   'reduce_health',
			'UI_remove_all_spells',
			   'remove_all_spells',
			'UI_remove_answer',
			   'remove_answer',
			'UI_remove_cont_items',
			   'remove_cont_items',
			'UI_remove_from_area',
			   'remove_from_area',
			'UI_remove_from_keyring',
			   'remove_from_keyring',
			'UI_remove_from_party',
			   'remove_from_party',
			'UI_remove_item',
			   'remove_item',
			'UI_remove_npc',
			   'remove_npc',
			'UI_remove_npc_face0',
			   'remove_npc_face0',
			'UI_remove_npc_face1',
			   'remove_npc_face1',
			'UI_remove_npc_face',
			   'remove_npc_face',
			'UI_remove_party_items',
			   'remove_party_items',
			'UI_remove_spell',
			   'remove_spell',
			'UI_restart_game',
			   'restart_game',
			'UI_resurrect',
			   'resurrect',
			'UI_resurrect_npc',
			   'resurrect_npc',
			'UI_revert_schedule',
			   'revert_schedule',
			'UI_roll_to_win',
			   'roll_to_win',
			'UI_run_endgame',
			   'run_endgame',
			'UI_run_schedule',
			   'run_schedule',
			'UI_save_pos',
			   'save_pos',
			'UI_select_from_menu2',
			   'select_from_menu2',
			'UI_select_from_menu',
			   'select_from_menu',
			'UI_set_alignment',
			   'set_alignment',
			'UI_set_attack_mode',
			   'set_attack_mode',
			'UI_set_barge_dir',
			   'set_barge_dir',
			'UI_set_camera',
			   'set_camera',
			'UI_set_conversation_slot',
			   'set_conversation_slot',
			'UI_set_intercept_item',
			   'set_intercept_item',
			'UI_set_item_flag',
			   'set_item_flag',
			'UI_set_item_frame',
			   'set_item_frame',
			'UI_set_item_frame_rot',
			   'set_item_frame_rot',
			'UI_set_item_quality',
			   'set_item_quality',
			'UI_set_item_quantity',
			   'set_item_quantity',
			'UI_set_item_shape',
			   'set_item_shape',
			'UI_set_last_created',
			   'set_last_created',
			'UI_set_lift',
			   'set_lift',
			'UI_set_light',
			   'set_light',
			'UI_set_new_schedules',
			   'set_new_schedules',
			'UI_set_npc_id',
			   'set_npc_id',
			'UI_set_npc_name',
			   'set_npc_name',
			'UI_set_npc_prop',
			   'set_npc_prop',
			'UI_set_opponent',
			   'set_opponent',
			'UI_set_oppressor',
			   'set_oppressor',
			'UI_set_orrery',
			   'set_orrery',
			'UI_set_path_failure',
			   'set_path_failure',
			'UI_set_polymorph',
			   'set_polymorph',
			'UI_set_schedule_type',
			   'set_schedule_type',
			'UI_set_temperature',
			   'set_temperature',
			'UI_set_time_palette',
			   'set_time_palette',
			'UI_set_timer',
			   'set_timer',
			'UI_set_to_attack',
			   'set_to_attack',
			'UI_set_usecode_fun',
			   'set_usecode_fun',
			'UI_set_weather',
			   'set_weather',
			'UI_show_npc_face0',
			   'show_npc_face0',
			'UI_show_npc_face1',
			   'show_npc_face1',
			'UI_show_npc_face',
			   'show_npc_face',
			'UI_si_display_map',
			   'si_display_map',
			'UI_si_path_run_usecode',
			   'si_path_run_usecode',
			'UI_sit_down',
			   'sit_down',
			'UI_sprite_effect',
			   'sprite_effect',
			'UI_start_speech',
			   'start_speech',
			'UI_stop_time',
			   'stop_time',
			'UI_summon',
			   'summon',
			'UI_telekenesis',
			   'telekenesis',
			'UI_teleport_to_saved_pos',
			   'teleport_to_saved_pos',
			'UI_update_last_created',
			   'update_last_created',
			'UI_view_tile',
			   'view_tile',
			'UI_wearing_fellowship',
			   'wearing_fellowship',
			'UI_wizard_eye',
			   'wizard_eye',
		),
		6 => array(				// Compiler directives
			'#line', '#include', '#game', '#autonumber', '#',
			),
		),
	'SYMBOLS' => array(
		'(', ')', '{', '}', '[', ']', '=', '+', '-', '*', '/', '!', '&', ':', '&lt;', '&gt;', '&lt;&lt;'
		),
	'CASE_SENSITIVE' => array(
		GESHI_COMMENTS => true,
		1 => true,
		2 => true,
		3 => true,
		4 => true,
		5 => true,
		6 => true,
		),
	'STYLES' => array(
		'KEYWORDS' => array(
			1 => 'color: #0000ff; font-weight: bold;',
			2 => 'color: #00C000; font-weight: bold;',
			3 => 'color: #008080;',
			4 => 'color: #800080; font-style: italic;',
			5 => 'color: #C000C0; font-weight: bold;',
			6 => 'color: #0000ff; font-weight: bold;',
			),
		'COMMENTS' => array(
			1 => 'color: #808080; font-style: italic;',
			2 => 'color: #0000ff;',
			'MULTI' => 'color: #808080; font-style: italic;'
			),
		'ESCAPE_CHAR' => array(
			0 => 'color: #800000; font-weight: bold;'
			),
		'BRACKETS' => array(
			0 => 'color: #808080;'
			),
		'STRINGS' => array(
			0 => 'color: #808000;'
			),
		'NUMBERS' => array(
			0 => 'color: #ff0000;'
			),
		'METHODS' => array(
			1 => 'color: #808080;',
			2 => 'color: #808080;'
			),
		'SYMBOLS' => array(
			0 => 'color: #808080;'
			),
		'REGEXPS' => array(
			),
		'SCRIPT' => array(
			)
		),
	'URLS' => array(
		1	=>	'',
		2	=>	'',
		3	=>	'http://seventowers.thefeudallands.ca/ucc_ref.php?TYPE=3&amp;DATAFILE={FNAME}',
		4	=>	'',
		5	=>	'http://seventowers.thefeudallands.ca/ucc_ref.php?TYPE=5&amp;DATAFILE={FNAME}',
		6	=>	'http://seventowers.thefeudallands.ca/ucc_ref.php?TYPE=6&amp;DATAFILE={FNAME}',
		),
	'OOLANG' => true,
	'OBJECT_SPLITTERS' => array(
		1 => '.',
		2 => '-&gt;',
		3 => '::',
		),
	'REGEXPS' => array(
		),
	'STRICT_MODE_APPLIES' => GESHI_NEVER,
	'SCRIPT_DELIMITERS' => array(
		),
	'HIGHLIGHT_STRICT_BLOCK' => array(
		)
);

?>
